---
delete.retention.ms: int(required=False)
max.message.bytes: int(required=False)
max.compaction.lag.ms: int(required=False)
message.timestamp.difference.max.ms: int(required=False)
message.timestamp.before.max.ms: int(required=False)
message.timestamp.after.max.ms: int(required=False)
message.timestamp.type: enum('CreateTime', 'LogAppendTime', required=False)
min.compaction.lag.ms: int(required=False)
min.insync.replicas: int(required=False)
retention.bytes: int(required=False)
retention.ms: int(required=False)
segment.bytes: int(required=False)
segment.ms: int(required=False)
confluent.key.schema.validation: bool(required=False)
confluent.value.schema.validation: bool(required=False)
confluent.key.subject.name.strategy: str(required=False)
confluent.value.subject.name.strategy: str(required=False)
