network_display_name             = "azu-net-dev-eastus-01"
region                           = "eastus"
private_link_dns_resolution      = "PRIVATE"
private_link_access_display_name = "azu-pla-dev-eastus-01"
customer_azure_subscription_id   = "00000000-0000-0000-0000-d6b16f9a0eba"
confluent_cloud_environment_name = "azu-env-d-eastus-01"
