name: CI Workflow for Kafka Client Resources

on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string
      cloud:
        required: true
        type: string
      env:
        required: true
        type: string
      pipeline_version:
        required: true
        type: string

jobs:
  validate-topic:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    env:
      FILE_NAME: ${{ inputs.file }}
      CLOUD_PROVIDER: ${{ inputs.cloud }}
      ENV: ${{ inputs.env }}
      PIPELINE_VERSION: ${{ inputs.pipeline_version }}

    steps:
      - name: Checkout kafka-iac
        uses: actions/checkout@v4
        with:
          repository: Psyncopate-Technologies/kafka-iac
          ref: v${{ inputs.pipeline_version }}
          path: kafka-iac

      - name: Checkout kafka-client-config
        uses: actions/checkout@v4
        with:
          repository: Psyncopate-Technologies/kafka-client-config
          path: kafka-client-config

      - name: Validate with Terragrunt
        working-directory: kafka-iac/cc-live/${{ env.ENV }}/topics
        run: |
          echo "Running Terragrunt validate for ${FILE_NAME}"
          terragrunt plan --terragrunt-config kafka-client-config/${FILE_NAME}
